spring.application.name=aduana-reportes-api
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@clases_high?TNS_ADMIN=X:/Analista/Proyectos/SistemaAduana/Wallet_clases
spring.datasource.username=ADMIN
spring.datasource.password=Computador2324.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

aduana.api.url=http://localhost:8080

spring.cloud.compatibility-verifier.enabled=false